---
- name: Download ES
  get_url:
    url: "https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/{{ elk_elasticsearch.version }}/elasticsearch-{{ elk_elasticsearch.version }}.deb"
    dest: "/home/{{ ansible_env.USER }}/downloads/elasticsearch-{{ elk_elasticsearch.version }}.deb"

- name: ES apt repo
  apt: deb=/home/{{ ansible_env.USER }}/downloads/elasticsearch-{{ elk_elasticsearch.version }}.deb
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install ES apt packages
  apt: pkg=elasticsearch update_cache=yes state=latest
  sudo: yes
  when: ansible_os_family == 'Debian'
  notify: Restart elasticsearch

- name: Curator PIP package
  pip: name=elasticsearch-curator state=latest
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch

- name: Make monit to look after ES
  template:
    src=elasticsearch.monitrc.conf.j2
    dest=/etc/monit/conf.d/elasticsearch.monitrc.conf
    owner=root group=root mode=644
  sudo: yes
  notify: Restart monit
